version: '3.8'

services:
  postgres:
    image: postgres:15
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
        - .prod.env

  web:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - postgres
    env_file:
        - .prod.env
#    command: bash
#    tty: true

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"

volumes:
  postgres:
