version: '3.9'

services:
  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .prod.env
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .prod.env
    restart: always

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    restart: always

volumes:
  postgres_data:
