version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
