version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - .envs/.local/.postgres

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .envs/.local/.django

volumes:
  postgres_data:
