# Generated by Django 4.2 on 2023-05-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='multilingualtext',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='multilingualtext',
            name='key',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='multilingualtext',
            unique_together={('key', 'languages')},
        ),
    ]
