# Generated by Django 4.2 on 2023-05-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideapp', '0002_alter_multilingualtext_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilingualtext',
            name='languages',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('uk', 'Ukrainian')], default='es', max_length=2),
        ),
    ]
